name: Deploy to AWS ECS

on:
  push:
    branches:
      - main  # Runs on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Authenticate to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 246651824707.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Docker Image
        run: |
          docker build -t myapp .
          docker tag myapp:latest 246651824707.dkr.ecr.us-east-1.amazonaws.com/myapp-repo:latest
          docker push 246651824707.dkr.ecr.us-east-1.amazonaws.com/myapp-repo:latest

      - name: Deploy to Amazon ECS
        run: |
          aws ecs update-service --cluster myapp-cluster --service myapp-service --force-new-deployment
